#https://github.com/poperigby/gruvbox-dark-yazi


# vim:fileencoding=utf-8:foldmethod=marker

# : Manager {{{

[manager]
cwd = { fg = "#E1AB14" }

# Hovered
hovered         = { fg = "#E1AB14", bg = "#3d3924" }
preview_hovered = { underline = true }

# Find
find_keyword  = { fg = "#AAAC65", italic = true }
find_position = { fg = "#68503B", bg = "reset", italic = true }

# Marker
marker_selected = { fg = "#AAAC65", bg = "#C6B984" }
marker_copied   = { fg = "#AAAC65", bg = "#C6B984" }
marker_cut      = { fg = "#fb4934", bg = "#fb4934" }

# Tab
tab_active   = { fg = "#282828", bg = "#504945" }
tab_inactive = { fg = "#a89984", bg = "#3c3836" }
tab_width    = 1

# Border
border_symbol = "│"
border_style  = { fg = "#e0be60" }

# : Status {{{

[status]
separator_open  = ""
separator_close = ""
separator_style = { fg = "#11100b", bg = "#211f17" }

# Mode
mode_normal = { fg = "#11100b", bg = "#82701a", bold = true }
mode_select = { fg = "#11100b", bg = "#82701a", bold = true }
mode_unset  = { fg = "#11100b", bg = "#82701a", bold = true }

# Progress
progress_label  = { fg = "#ebdbb2", bold = true }
progress_normal = { fg = "#504945", bg = "#3c3836" }
progress_error  = { fg = "#fb4934", bg = "#3c3836" }

# Permissions
permissions_t = { fg = "#504945" }
permissions_r = { fg = "#fcf7b5" }
permissions_w = { fg = "#fb4934" }
permissions_x = { fg = "#baac89" }
permissions_s = { fg = "#665c54" }

# : }}}


# : Input {{{

[input]
border   = { fg = "#eabf48" }
title    = {}
value    = {}
selected = { reversed = true }

# : }}}


# : Select {{{

[select]
border   = { fg = "#504945" }
active   = { fg = "#68503B" }
inactive = {}

# : }}}


# : Tasks {{{

[tasks]
border  = { fg = "#504945" }
title   = {}
hovered = { underline = true }

# : }}}


# : Which {{{

[which]
mask            = { bg = "#383528" }
cand            = { fg = "#e5e2c3" }
rest            = { fg = "#928374" }
desc            = { fg = "#6b6558" }
separator       = "  "
separator_style = { fg = "#ba8c10" }

# : }}}


# : Help {{{

[help]
on      = { fg = "#68503B" }
exec    = { fg = "#83a598" }
desc    = { fg = "#928374" }
hovered = { bg = "#504945", bold = true }
footer  = { fg = "#3c3836", bg = "#a89984" }

# : }}}


# : File-specific styles {{{

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#AAAC65" },

    # Videos
    { mime = "video/*", fg = "#AAAC65" },
    { mime = "audio/*", fg = "#355148" },

    # Archives
    { mime = "application/zip",             fg = "#68503B" },
    { mime = "application/gzip",            fg = "#68503B" },
    { mime = "application/x-tar",           fg = "#68503B" },
    { mime = "application/x-bzip",          fg = "#68503B" },
    { mime = "application/x-bzip2",         fg = "#68503B" },
    { mime = "application/x-7z-compressed", fg = "#68503B" },
    { mime = "application/x-rar",           fg = "#68503B" },

    # Fallback
    { name = "*", fg = "#8c865d" }, 
    { name = "*/", fg = "#635d3d" }
]

# : }}}
